### ISSUE TITLE
Challenge 1 Feedback

### ISSUE THREAD

**Issue by meredithcat** [timomak/cs-2.2#1]
Challenge 1 Feedback: 10/20
Code based on Challenge 1 Rubric

Overall looks good! Need to correct code to give desired output. However I like that you have an eval loop for manual testing.

- Solution: 1 (x2 = 2)
  - Code runs correctly on Graph but not Digraph
  - Code does not output vertices and edges in desired format

- Documentation: 3
  - All graph functions/classes include docstrings. Could also include docstrings for the read_text method to indicate its purpose and result.

- Organization: 3
  - File separation looks good; code is loosely coupled

- Testing: 2
  - No tests for the read_text method.
  - Testing looks good for Graph and Vertex classes

**Comment by timomak** [comment]
Awesome! I fixed up the output to be in the proper format for challenge 1!
